### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by sarathkcm** [LucasReade/Contextual.js#1]
Is this library usable in other projects? What are the licence terms?

**Comment by LucasReade** [comment]
Please feel free to use this project in others. I will get round to updating the license on the project when im next at my computer.

**Comment by sarathkcm** [comment]
Thank you. :) 
Currently evaluating a few options available, your demo page is compellingly good.

**Comment by LucasReade** [comment]
As you're the first person, if there are any features you can think of which might make Contextual.js more compelling please let me know :)
