### ISSUE TITLE
Add support for subitems UI 

### ISSUE THREAD

**Issue by happyContexUser** [LucasReade/Contextual.js#11]
Suggestion: As a user, I want to be able to open sub menu items on the right side of the menu instead from the bottom (attached picture).

![6565](https://user-images.githubusercontent.com/61791232/75890385-f7641e00-5e36-11ea-8569-6cc520c8e536.jpg)

**Comment by happyContexUser** [comment]
Thank you!

**Comment by LucasReade** [comment]
There is a branch called hoverMenu, there is a new type in the contextual menu called "hovermenu" it works exactly the same as a submenu. Should be going into master soon.

**Comment by LucasReade** [comment]
"hovermenu" type should solve this functionality.
