### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by EV-soft** [LucasReade/Contextual.js#2]
demo.html dont work.
The demo on https://www.cssscript.com/demo/context-menu-contextual/ do work, but is not up to date.
EDIT: 
Dont work with Right-click! - but with left-Click  it is ok!
New EDIT:
The menu is not visible because it is behind the default context menu!

**Comment by LucasReade** [comment]
If you are going to use the menu on a right click you need to prevent the default menu from showing before the contextual menu, basic example to remove the context menu would be:

```
document.addEventListener('contextmenu', event => {
    event.preventDefault();
    //Add contextual menu here
});
```

**Comment by EV-soft** [comment]
In the demo you might have one button with the text "Context" (= right click) and another with the text "Click me" (left click)

**Comment by LucasReade** [comment]
Added it :)

**Comment by EV-soft** [comment]
Excellent...
Could you also add examples of using icons?
