### ISSUE TITLE
Add a header

### ISSUE THREAD

**Issue by EV-soft** [LucasReade/Contextual.js#5]
Suggestion: Enables you to display a header with different background and information about the object at the top.

Example:
![billede](https://user-images.githubusercontent.com/21997911/65896836-443a5900-e3ae-11e9-8a3f-91cac6124a47.png)

**Comment by LucasReade** [comment]
How about some sort of customHeader attribute which allows you to add your own mark up into the header? Also headerColor attribute?

**Comment by EV-soft** [comment]
Yes. 
I will take a closer look at type:'custom', whether it can be used.

**Comment by LucasReade** [comment]
I think I will update the 'custom' type to work more like this rather than how it currently works.

**Comment by LucasReade** [comment]
> 
> 
> Yes.
> I will take a closer look at type:'custom', whether it can be used.

The custom type should be able to help out with this issue on the newest version

**Comment by EV-soft** [comment]
I've been working on a demo: 
[demo.zip](https://github.com/LucasReade/Contextual.js/files/3707566/demo.zip)
showing a header and where toolTip works.
Can it be used?

**Comment by EV-soft** [comment]
Here are a GIF-demo:
![output_Fd2vl3](https://user-images.githubusercontent.com/21997911/66512511-684a1880-ead9-11e9-8a0b-751a24b71771.gif)

**Comment by LucasReade** [comment]
The "custom" type should be a feature which allows this.
